### ISSUE TITLE
V1.0: Features & Todo List

### ISSUE THREAD

**Issue by zfben** [EverInsight/EverInsight#4]
- [ ] **Multiple Local Vaults**: Organize your data securely with several isolated vaults on your device.
- [ ] **Simple Sync Server**: Easily synchronize your data between devices with a minimalist server setup.
- [ ] **Text and View Modes**: Switch between a text-based editing mode and a visual view for a flexible user experience.
- [ ] **Local MDX Support**: Create rich content using Markdown (MDX) files directly within the application.
